/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlataformaDeEventosRouteImport } from './routes/plataforma-de-eventos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlataformaDeEventosRoute = PlataformaDeEventosRouteImport.update({
  id: '/plataforma-de-eventos',
  path: '/plataforma-de-eventos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/plataforma-de-eventos': typeof PlataformaDeEventosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/plataforma-de-eventos': typeof PlataformaDeEventosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/plataforma-de-eventos': typeof PlataformaDeEventosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/plataforma-de-eventos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/plataforma-de-eventos'
  id: '__root__' | '/' | '/plataforma-de-eventos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlataformaDeEventosRoute: typeof PlataformaDeEventosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plataforma-de-eventos': {
      id: '/plataforma-de-eventos'
      path: '/plataforma-de-eventos'
      fullPath: '/plataforma-de-eventos'
      preLoaderRoute: typeof PlataformaDeEventosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlataformaDeEventosRoute: PlataformaDeEventosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
